// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbll1bwQyjDVwb6k6nvXxABi5wR5WEBs',
    appId: '1:1070112538538:web:3963f15fb7660617cfb5d3',
    messagingSenderId: '1070112538538',
    projectId: 'interview-fd047',
    authDomain: 'interview-fd047.firebaseapp.com',
    storageBucket: 'interview-fd047.firebasestorage.app',
    measurementId: 'G-405S8506DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk_-daBA3xFrYgIdJ83yI1gT6iBHsjf_A',
    appId: '1:1070112538538:android:ce373c2c56094fe1cfb5d3',
    messagingSenderId: '1070112538538',
    projectId: 'interview-fd047',
    storageBucket: 'interview-fd047.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjmLl_PH-NSMIT4FDv6VPwB3_dU58Ev4M',
    appId: '1:1070112538538:ios:eb35f9420fdeeae7cfb5d3',
    messagingSenderId: '1070112538538',
    projectId: 'interview-fd047',
    storageBucket: 'interview-fd047.firebasestorage.app',
    iosBundleId: 'com.example.thapasyaInterviewNov14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjmLl_PH-NSMIT4FDv6VPwB3_dU58Ev4M',
    appId: '1:1070112538538:ios:eb35f9420fdeeae7cfb5d3',
    messagingSenderId: '1070112538538',
    projectId: 'interview-fd047',
    storageBucket: 'interview-fd047.firebasestorage.app',
    iosBundleId: 'com.example.thapasyaInterviewNov14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqbll1bwQyjDVwb6k6nvXxABi5wR5WEBs',
    appId: '1:1070112538538:web:29115f5753d14603cfb5d3',
    messagingSenderId: '1070112538538',
    projectId: 'interview-fd047',
    authDomain: 'interview-fd047.firebaseapp.com',
    storageBucket: 'interview-fd047.firebasestorage.app',
    measurementId: 'G-5WWMEC1CBX',
  );
}
